# Generated by Django 4.1 on 2022-08-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(blank=True, max_length=20, null=True)),
                ('note_text', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_edited', models.DateTimeField(auto_now_add=True)),
                ('note_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.noteslist')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
