# Generated by Django 4.1 on 2022-08-19 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_taskitem_delete_note_delete_noteslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='category',
            field=models.ForeignKey(choices=[('DEFAULT', 'DEFAULT'), ('PERSONAL', 'PERSONAL'), ('SHOPPING', 'SHOPPING'), ('WISHLIST', 'WISHLIST'), ('WORK', 'WORK')], default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='notes.category'),
        ),
    ]
