# Generated by Django 4.1 on 2022-08-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_category_default_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='default_categorys',
        ),
    ]
