# Generated by Django 4.1 on 2022-08-21 12:51

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_remove_category_default_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[notes.models.Category.choice_or_make]),
        ),
    ]
