# Generated by Django 4.1 on 2022-08-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_defaultcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultCategories',
        ),
    ]
