# Generated by Django 4.1 on 2022-08-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_delete_defaultcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.user'),
        ),
    ]
