# Generated by Django 4.1 on 2022-08-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_user_alter_taskitem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.user'),
        ),
    ]
