# Generated by Django 4.1 on 2022-08-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_alter_taskitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={},
        ),
    ]
